use std::env;
use std::process;

pub mod command;

fn main() {
    let args: Vec<String> = env::args().collect();
    
    // Get the command name (either from argv[0] or argv[1])
    let cmd_name = if args.len() > 1 {
        // Called as: nullbox <command> [args...]
        &args[1]
    } else {
        // Called as symlink: <command> [args...]
        let exe_name = args[0].split(['/', '\\']).last().unwrap_or("nullbox");
        let name = exe_name.trim_end_matches(".exe");
        if name == "nullbox" {
            print_usage();
            process::exit(0);
        }
        name
    };

    let cmd_args = if args.len() > 1 && &args[1] == cmd_name {
        &args[2..]
    } else {
        &args[1..]
    };

    let result = match cmd_name {
        "acpi" => command::acpi::execute(cmd_args),
        "alias" => command::alias::execute(cmd_args),
        "ar" => command::ar::execute(cmd_args),
        "arch" => command::arch::execute(cmd_args),
        "arp" => command::arp::execute(cmd_args),
        "at" => command::at::execute(cmd_args),
        "attrib" => command::attrib::execute(cmd_args),
        "awk" => command::awk::execute(cmd_args),
        "b2sum" => command::b2sum::execute(cmd_args),
        "badblocks" => command::badblocks::execute(cmd_args),
        "banner" => command::banner::execute(cmd_args),
        "base32" => command::base32::execute(cmd_args),
        "base64" => command::base64::execute(cmd_args),
        "basenc" => command::basenc::execute(cmd_args),
        "basename" => command::basename::execute(cmd_args),
        "batch" => command::batch::execute(cmd_args),
        "bc" => command::bc::execute(cmd_args),
        "bg" => command::bg::execute(cmd_args),
        "blkid" => command::blkid::execute(cmd_args),
        "bootctl" => command::bootctl::execute(cmd_args),
        "busctl" => command::busctl::execute(cmd_args),
        "cal" => command::cal::execute(cmd_args),
        "cat" => command::cat::execute(cmd_args),
        "cd" => command::cd::execute(cmd_args),
        "chattr" => command::chattr::execute(cmd_args),
        "chgrp" => command::chgrp::execute(cmd_args),
        "chkconfig" => command::chkconfig::execute(cmd_args),
        "chmod" => command::chmod::execute(cmd_args),
        "chown" => command::chown::execute(cmd_args),
        "chroot" => command::chroot::execute(cmd_args),
        "cksum" => command::cksum::execute(cmd_args),
        "cksum256" => command::cksum256::execute(cmd_args),
        "clear" | "clr" | "cls" => command::clear::execute(cmd_args),
        "cmp" => command::cmp::execute(cmd_args),
        "col" => command::col::execute(cmd_args),
        "colrm" => command::colrm::execute(cmd_args),
        "column" => command::column::execute(cmd_args),
        "comm" => command::comm::execute(cmd_args),
        "comp" => command::comp::execute(cmd_args),
        "compress" => command::compress::execute(cmd_args),
        "coredumpctl" => command::coredumpctl::execute(cmd_args),
        "cp" => command::cp::execute(cmd_args),
        "cpuinfo" => command::cpuinfo::execute(cmd_args),
        "crc32" => command::crc32::execute(cmd_args),
        "crontab" => command::crontab::execute(cmd_args),
        "csplit" => command::csplit::execute(cmd_args),
        "curl" => command::curl::execute(cmd_args),
        "cut" => command::cut::execute(cmd_args),
        "date" => command::date::execute(cmd_args),
        "dc" => command::dc::execute(cmd_args),
        "dd" => command::dd::execute(cmd_args),
        "deroff" => command::deroff::execute(cmd_args),
        "df" => command::df::execute(cmd_args),
        "diff" => command::diff::execute(cmd_args),
        "dig" => command::dig::execute(cmd_args),
        "dircolors" => command::dircolors::execute(cmd_args),
        "dirname" => command::dirname::execute(cmd_args),
        "disown" => command::disown::execute(cmd_args),
        "dmesg" => command::dmesg::execute(cmd_args),
        "dmidecode" => command::dmidecode::execute(cmd_args),
        "dos2unix" => command::dos2unix::execute(cmd_args),
        "doskey" => command::doskey::execute(cmd_args),
        "du" => command::du::execute(cmd_args),
        "dumpe2fs" => command::dumpe2fs::execute(cmd_args),
        "e2fsck" => command::e2fsck::execute(cmd_args),
        "echo" => command::echo::execute(cmd_args),
        "edlin" => command::edlin::execute(cmd_args),
        "egrep" => command::egrep::execute(cmd_args),
        "eject" => command::eject::execute(cmd_args),
        "env" => command::env::execute(cmd_args),
        "ethtool" => command::ethtool::execute(cmd_args),
        "exec" => command::exec::execute(cmd_args),
        "expand" => command::expand::execute(cmd_args),
        "expr" => command::expr::execute(cmd_args),
        "factor" => command::factor::execute(cmd_args),
        "false" => command::false_cmd::execute(cmd_args),
        "fc" => command::fc::execute(cmd_args),
        "fdisk" => command::fdisk::execute(cmd_args),
        "fg" => command::fg::execute(cmd_args),
        "fgrep" => command::fgrep::execute(cmd_args),
        "file" => command::file::execute(cmd_args),
        "find" => command::find::execute(cmd_args),
        "finger" => command::finger::execute(cmd_args),
        "fmt" => command::fmt::execute(cmd_args),
        "fold" => command::fold::execute(cmd_args),
        "free" => command::free::execute(cmd_args),
        "fsck" => command::fsck::execute(cmd_args),
        "ftp" => command::ftp::execute(cmd_args),
        "getent" => command::getent::execute(cmd_args),
        "getfacl" => command::getfacl::execute(cmd_args),
        "grep" => command::grep::execute(cmd_args),
        "groups" => command::groups::execute(cmd_args),
        "gunzip" => command::gunzip::execute(cmd_args),
        "gzip" => command::gzip::execute(cmd_args),
        "halt" => command::halt::execute(cmd_args),
        "hash" => command::hash::execute(cmd_args),
        "hdparm" => command::hdparm::execute(cmd_args),
        "head" => command::head::execute(cmd_args),
        "help" => command::help::execute(cmd_args),
        "hexdump" => command::hexdump::execute(cmd_args),
        "history" => command::history::execute(cmd_args),
        "homectl" => command::homectl::execute(cmd_args),
        "host" => command::host::execute(cmd_args),
        "hostname" => command::hostname::execute(cmd_args),
        "hostnamectl" => command::hostnamectl::execute(cmd_args),
        "htop" => command::htop::execute(cmd_args),
        "hwinfo" => command::hwinfo::execute(cmd_args),
        "iconv" => command::iconv::execute(cmd_args),
        "id" => command::id::execute(cmd_args),
        "ifconfig" => command::ifconfig::execute(cmd_args),
        "insmod" => command::insmod::execute(cmd_args),
        "install" => command::install::execute(cmd_args),
        "inxi" => command::inxi::execute(cmd_args),
        "ionice" => command::ionice::execute(cmd_args),
        "iostat" => command::iostat::execute(cmd_args),
        "iotop" => command::iotop::execute(cmd_args),
        "ip" => command::ip::execute(cmd_args),
        "ipconfig" => command::ipconfig::execute(cmd_args),
        "iwconfig" => command::iwconfig::execute(cmd_args),
        "jobs" => command::jobs::execute(cmd_args),
        "join" => command::join::execute(cmd_args),
        "journalctl" => command::journalctl::execute(cmd_args),
        "kill" => command::kill::execute(cmd_args),
        "killall" => command::killall::execute(cmd_args),
        "label" => command::label::execute(cmd_args),
        "last" => command::last::execute(cmd_args),
        "ldd" => command::ldd::execute(cmd_args),
        "ldconfig" => command::ldconfig::execute(cmd_args),
        "less" => command::less::execute(cmd_args),
        "link" => command::link::execute(cmd_args),
        "ln" => command::ln::execute(cmd_args),
        "locale" => command::locale::execute(cmd_args),
        "localectl" => command::localectl::execute(cmd_args),
        "locate" => command::locate::execute(cmd_args),
        "loginctl" => command::loginctl::execute(cmd_args),
        "logger" => command::logger::execute(cmd_args),
        "logname" => command::logname::execute(cmd_args),
        "look" => command::look::execute(cmd_args),
        "lsattr" => command::lsattr::execute(cmd_args),
        "lsblk" => command::lsblk::execute(cmd_args),
        "lscpu" => command::lscpu::execute(cmd_args),
        "lshw" => command::lshw::execute(cmd_args),
        "lsmod" => command::lsmod::execute(cmd_args),
        "lsof" => command::lsof::execute(cmd_args),
        "lspci" => command::lspci::execute(cmd_args),
        "lsusb" => command::lsusb::execute(cmd_args),
        "ltrace" => command::ltrace::execute(cmd_args),
        "machinectl" => command::machinectl::execute(cmd_args),
        "make" => command::make::execute(cmd_args),
        "md5" => command::md5::execute(cmd_args),
        "md5sum" => command::md5sum::execute(cmd_args),
        "meminfo" => command::meminfo::execute(cmd_args),
        "mesg" => command::mesg::execute(cmd_args),
        "mkdir" => command::mkdir::execute(cmd_args),
        "mkfifo" => command::mkfifo::execute(cmd_args),
        "mkfs" => command::mkfs::execute(cmd_args),
        "mknod" => command::mknod::execute(cmd_args),
        "mkswap" => command::mkswap::execute(cmd_args),
        "mktemp" => command::mktemp::execute(cmd_args),
        "modprobe" => command::modprobe::execute(cmd_args),
        "more" => command::more::execute(cmd_args),
        "mount" => command::mount::execute(cmd_args),
        "mpstat" => command::mpstat::execute(cmd_args),
        "mv" => command::mv::execute(cmd_args),
        "netstat" => command::netstat::execute(cmd_args),
        "networkctl" => command::networkctl::execute(cmd_args),
        "nice" => command::nice::execute(cmd_args),
        "nl" => command::nl::execute(cmd_args),
        "nm" => command::nm::execute(cmd_args),
        "nohup" => command::nohup::execute(cmd_args),
        "nproc" => command::nproc::execute(cmd_args),
        "nslookup" => command::nslookup::execute(cmd_args),
        "numfmt" => command::numfmt::execute(cmd_args),
        "objdump" => command::objdump::execute(cmd_args),
        "od" => command::od::execute(cmd_args),
        "oomctl" => command::oomctl::execute(cmd_args),
        "parted" => command::parted::execute(cmd_args),
        "paste" => command::paste::execute(cmd_args),
        "patch" => command::patch::execute(cmd_args),
        "pathchk" => command::pathchk::execute(cmd_args),
        "pathping" => command::pathping::execute(cmd_args),
        "perf" => command::perf::execute(cmd_args),
        "pgrep" => command::pgrep::execute(cmd_args),
        "pidstat" => command::pidstat::execute(cmd_args),
        "ping" => command::ping::execute(cmd_args),
        "pinky" => command::pinky::execute(cmd_args),
        "pkill" => command::pkill::execute(cmd_args),
        "pmap" => command::pmap::execute(cmd_args),
        "portablectl" => command::portablectl::execute(cmd_args),
        "pr" => command::pr::execute(cmd_args),
        "printcap" => command::printcap::execute(cmd_args),
        "printenv" => command::printenv::execute(cmd_args),
        "printf" => command::printf::execute(cmd_args),
        "ps" => command::ps::execute(cmd_args),
        "ptx" => command::ptx::execute(cmd_args),
        "pwd" => command::pwd::execute(cmd_args),
        "pwdx" => command::pwdx::execute(cmd_args),
        "ranlib" => command::ranlib::execute(cmd_args),
        "readlink" => command::readlink::execute(cmd_args),
        "realpath" => command::realpath::execute(cmd_args),
        "reboot" => command::reboot::execute(cmd_args),
        "rx" | "regex" => command::regex::execute(cmd_args),
        "renice" => command::renice::execute(cmd_args),
        "reset" => command::reset::execute(cmd_args),
        "resize2fs" => command::resize2fs::execute(cmd_args),
        "resolvectl" => command::resolvectl::execute(cmd_args),
        "rev" => command::rev::execute(cmd_args),
        "del" | "rm" => command::rm::execute(cmd_args),
        "rmdir" => command::rmdir::execute(cmd_args),
        "rmmod" => command::rmmod::execute(cmd_args),
        "route" => command::route::execute(cmd_args),
        "runcon" => command::runcon::execute(cmd_args),
        "sar" => command::sar::execute(cmd_args),
        "script" => command::script::execute(cmd_args),
        "sed" => command::sed::execute(cmd_args),
        "sensors" => command::sensors::execute(cmd_args),
        "seq" => command::seq::execute(cmd_args),
        "service" => command::service::execute(cmd_args),
        "setfacl" => command::setfacl::execute(cmd_args),
        "sha1" => command::sha1::execute(cmd_args),
        "sha1sum" => command::sha1sum::execute(cmd_args),
        "sha256" => command::sha256::execute(cmd_args),
        "sha256sum" => command::sha256sum::execute(cmd_args),
        "sha384" => command::sha384::execute(cmd_args),
        "sha384sum" => command::sha384sum::execute(cmd_args),
        "sha512" => command::sha512::execute(cmd_args),
        "sha512sum" => command::sha512sum::execute(cmd_args),
        "shred" => command::shred::execute(cmd_args),
        "shuf" => command::shuf::execute(cmd_args),
        "shutdown" => command::shutdown::execute(cmd_args),
        "size" => command::size::execute(cmd_args),
        "slabtop" => command::slabtop::execute(cmd_args),
        "sleep" => command::sleep::execute(cmd_args),
        "smartctl" => command::smartctl::execute(cmd_args),
        "sort" => command::sort::execute(cmd_args),
        "split" => command::split::execute(cmd_args),
        "ss" => command::ss::execute(cmd_args),
        "stat" => command::stat::execute(cmd_args),
        "stdbuf" => command::stdbuf::execute(cmd_args),
        "strace" => command::strace::execute(cmd_args),
        "strings" => command::strings::execute(cmd_args),
        "strip" => command::strip::execute(cmd_args),
        "stty" => command::stty::execute(cmd_args),
        "su" => command::su::execute(cmd_args),
        "sum" => command::sum::execute(cmd_args),
        "suspend" => command::suspend::execute(cmd_args),
        "swapon" => command::swapon::execute(cmd_args),
        "swapoff" => command::swapoff::execute(cmd_args),
        "sync" => command::sync::execute(cmd_args),
        "sysctl" => command::sysctl::execute(cmd_args),
        "systemctl" => command::systemctl::execute(cmd_args),
        "tabs" => command::tabs::execute(cmd_args),
        "tac" => command::tac::execute(cmd_args),
        "tail" => command::tail::execute(cmd_args),
        "talk" => command::talk::execute(cmd_args),
        "tar" => command::tar::execute(cmd_args),
        "tcpdump" => command::tcpdump::execute(cmd_args),
        "tee" => command::tee::execute(cmd_args),
        "telnet" => command::telnet::execute(cmd_args),
        "test" => command::test::execute(cmd_args),
        "time" => command::time::execute(cmd_args),
        "timedatectl" => command::timedatectl::execute(cmd_args),
        "timeout" => command::timeout::execute(cmd_args),
        "top" => command::top::execute(cmd_args),
        "touch" => command::touch::execute(cmd_args),
        "tr" => command::tr::execute(cmd_args),
        "traceroute" => command::traceroute::execute(cmd_args),
        "tracert" => command::tracert::execute(cmd_args),
        "tree" => command::tree::execute(cmd_args),
        "true" => command::true_cmd::execute(cmd_args),
        "truncate" => command::truncate::execute(cmd_args),
        "tsort" => command::tsort::execute(cmd_args),
        "tty" => command::tty::execute(cmd_args),
        "tune2fs" => command::tune2fs::execute(cmd_args),
        "type" => command::type_cmd::execute(cmd_args),
        "udevadm" => command::udevadm::execute(cmd_args),
        "ulimit" => command::ulimit::execute(cmd_args),
        "umask" => command::umask::execute(cmd_args),
        "umount" => command::umount::execute(cmd_args),
        "uname" => command::uname::execute(cmd_args),
        "uncompress" => command::uncompress::execute(cmd_args),
        "unexpand" => command::unexpand::execute(cmd_args),
        "uniq" => command::uniq::execute(cmd_args),
        "unix2dos" => command::unix2dos::execute(cmd_args),
        "unlink" => command::unlink::execute(cmd_args),
        "unset" => command::unset::execute(cmd_args),
        "unzip" => command::unzip::execute(cmd_args),
        "update-rc.d" => command::update_rc::execute(cmd_args),
        "uptime" => command::uptime::execute(cmd_args),
        "userdbctl" => command::userdbctl::execute(cmd_args),
        "users" => command::users::execute(cmd_args),
        "vdir" => command::vdir::execute(cmd_args),
        "ver" => command::ver::execute(cmd_args),
        "vmstat" => command::vmstat::execute(cmd_args),
        "vol" => command::vol::execute(cmd_args),
        "w" => command::w::execute(cmd_args),
        "wait" => command::wait::execute(cmd_args),
        "wall" => command::wall::execute(cmd_args),
        "watch" => command::watch::execute(cmd_args),
        "wc" => command::wc::execute(cmd_args),
        "wget" => command::wget::execute(cmd_args),
        "where" => command::where_cmd::execute(cmd_args),
        "which" => command::which::execute(cmd_args),
        "who" => command::who::execute(cmd_args),
        "whoami" => command::whoami::execute(cmd_args),
        "whois" => command::whois::execute(cmd_args),
        "write" => command::write::execute(cmd_args),
        "xargs" => command::xargs::execute(cmd_args),
        "xxd" => command::xxd::execute(cmd_args),
        "yes" => command::yes::execute(cmd_args),
        "zcat" => command::zcat::execute(cmd_args),
        "zip" => command::zip::execute(cmd_args),
        "dir" | "ls" => command::ls::execute(cmd_args),
        _ => {
            eprintln!("nullbox: unknown command '{}'", cmd_name);
            print_usage();
            process::exit(1);
        }
    };

    if let Err(e) = result {
        eprintln!("{}: {}", cmd_name, e);
        process::exit(1);
    }
}

fn print_usage() {
    println!("nullbox - A modern BusyBox-like utility");
    println!("\nUsage: nullbox <command> [args...]");
    println!("\n250+ Available commands inspired by DOS, Linux, Unix and modern tools:");
    println!("  File Operations: cat cp mv rm del mkdir rmdir touch ln link");
    println!("  Text Processing: grep sed awk cut sort uniq head tail wc tr");
    println!("  System Info: uname hostname uptime whoami id ps top free df");
    println!("  Network: ping curl wget netstat ifconfig ip nslookup dig");
    println!("  Compression: gzip gunzip zip unzip tar compress uncompress");
    println!("  Checksums: md5 sha1 sha256 sha384 sha512 cksum crc32 b2sum");
    println!("  And many more... Run 'nullbox help' for full list");
}
